"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRepositoriosAutorizados as useRepositories, useSessao } from "@/components/providers/session-provider";
import { useToast } from "@/components/ui/toast";
import { PageIntro, SectionLabel, StatusPill, SurfaceCard } from "@/components/ui/workspace-primitives";
import type { Pedido } from "@/lib/domain/entities";
import type { EntregaPedido, ModalidadeEntrega, StatusEntrega } from "@/lib/domain/entrega";
import { papelTemPermissao, PERMISSOES } from "@/lib/rbac";

const LABEL_MODALIDADE: Record<ModalidadeEntrega, string> = { retirada: "Retirada", entrega_propria: "Entrega própria", motoboy: "Motoboy", transportadora: "Transportadora", outro: "Outro" };
const LABEL_STATUS: Record<StatusEntrega, string> = { pronto: "Pronto", aguardando_retirada: "Aguardando retirada", saiu_para_entrega: "Saiu para entrega", entregue: "Entregue", falha_entrega: "Falha na entrega" };
const tom = (s: StatusEntrega) => s === "entregue" ? "success" as const : s === "falha_entrega" ? "danger" as const : s === "pronto" ? "accent" as const : "warning" as const;

export default function EntregasPage() {
  const repos = useRepositories(), { sessao } = useSessao(), { showToast } = useToast(); const empresaId = sessao?.empresaAtiva?.id, usuarioId = sessao?.usuario.id;
  const podeGerenciar = sessao?.empresaAtiva ? papelTemPermissao(sessao.empresaAtiva.papel, PERMISSOES.ENTREGA_GERENCIAR) : false;
  const [pedidos, setPedidos] = useState<Pedido[]>([]), [entregas, setEntregas] = useState<EntregaPedido[]>([]), [numerosPedido, setNumerosPedido] = useState<Record<string, string>>({}), [pedidoId, setPedidoId] = useState(""), [modalidade, setModalidade] = useState<ModalidadeEntrega>("retirada"), [endereco, setEndereco] = useState(""), [previsao, setPrevisao] = useState(""), [transportadora, setTransportadora] = useState(""), [codigoRastreio, setCodigoRastreio] = useState(""), [responsavel, setResponsavel] = useState(""), [recebedor, setRecebedor] = useState(""), [comprovante, setComprovante] = useState(""), [observacao, setObservacao] = useState("");
  async function carregar() { if (!empresaId) return; const [ps, resumos] = await Promise.all([podeGerenciar ? repos.pedidos.listar(empresaId) : Promise.resolve([]), repos.entregas.listarResumos(empresaId)]); const es = resumos.map((r) => r.entrega); setPedidos(ps.filter((p) => p.statusEntrega !== "cancelado")); setEntregas(es); setNumerosPedido(Object.fromEntries(resumos.map((r) => [r.entrega.pedidoId, r.pedidoNumero]))); if (!pedidoId) setPedidoId(ps.find((p) => !es.some((e) => e.pedidoId === p.id) && p.statusEntrega !== "cancelado")?.id ?? ""); }
  useEffect(() => { void carregar(); }, [empresaId]); // eslint-disable-line react-hooks/exhaustive-deps
  async function executar(acao: () => Promise<unknown>, mensagem: string) { try { await acao(); showToast(mensagem, "success"); await carregar(); } catch (erro) { showToast(erro instanceof Error ? erro.message : "Falha na entrega.", "error"); } }
  if (!empresaId || !usuarioId) return null;
  return <div className="flex flex-col gap-4"><PageIntro eyebrow="Expedição" title="Entregas" description="Retirada, entrega própria, motoboy e transportadora com estados, falhas, comprovante e histórico imutável." aside={<StatusPill tone="accent">{entregas.filter((e) => e.status !== "entregue").length} em aberto</StatusPill>} />
    {podeGerenciar ? <SurfaceCard className="p-5"><SectionLabel>Preparar Pedido pronto</SectionLabel><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><div><label htmlFor="entrega-pedido" className="workspace-label">Pedido</label><select id="entrega-pedido" className="workspace-input" value={pedidoId} onChange={(e) => setPedidoId(e.target.value)}><option value="">Selecione</option>{pedidos.filter((p) => !entregas.some((e) => e.pedidoId === p.id)).map((p) => <option key={p.id} value={p.id}>{p.numero}</option>)}</select></div><div><label htmlFor="entrega-modalidade" className="workspace-label">Modalidade</label><select id="entrega-modalidade" className="workspace-input" value={modalidade} onChange={(e) => setModalidade(e.target.value as ModalidadeEntrega)}>{Object.entries(LABEL_MODALIDADE).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></div><div><label htmlFor="entrega-previsao" className="workspace-label">Previsão</label><input id="entrega-previsao" type="date" className="workspace-input" value={previsao} onChange={(e) => setPrevisao(e.target.value)} /></div>{modalidade !== "retirada" ? <div className="sm:col-span-2"><label htmlFor="entrega-endereco" className="workspace-label">Endereço</label><input id="entrega-endereco" className="workspace-input" value={endereco} onChange={(e) => setEndereco(e.target.value)} /></div> : null}<div><label htmlFor="entrega-responsavel" className="workspace-label">Responsável</label><input id="entrega-responsavel" className="workspace-input" value={responsavel} onChange={(e) => setResponsavel(e.target.value)} /></div>{modalidade === "transportadora" ? <><div><label htmlFor="entrega-transportadora" className="workspace-label">Transportadora</label><input id="entrega-transportadora" className="workspace-input" value={transportadora} onChange={(e) => setTransportadora(e.target.value)} /></div><div><label htmlFor="entrega-rastreio" className="workspace-label">Código de rastreio</label><input id="entrega-rastreio" className="workspace-input" value={codigoRastreio} onChange={(e) => setCodigoRastreio(e.target.value)} /></div></> : null}</div><button className="workspace-button-primary mt-3" onClick={() => void executar(() => repos.entregas.preparar(empresaId, { pedidoId, modalidade, endereco, previsao: previsao || null, transportadora, codigoRastreio, responsavelEntrega: responsavel, operacaoId: crypto.randomUUID() }, usuarioId), "Pedido marcado como pronto.")}>Preparar entrega</button></SurfaceCard> : null}
    <div className="grid gap-4">{entregas.map((e) => <SurfaceCard key={e.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div>{podeGerenciar ? <Link href={`/pedidos/${e.pedidoId}`} className="font-semibold underline">{numerosPedido[e.pedidoId]}</Link> : <p className="font-semibold">{numerosPedido[e.pedidoId]}</p>}<p className="text-sm text-(--text-secondary)">{LABEL_MODALIDADE[e.modalidade]}{e.previsao ? ` · previsão ${e.previsao.split("-").reverse().join("/")}` : ""}</p></div><StatusPill tone={tom(e.status)}>{LABEL_STATUS[e.status]}</StatusPill></div>{e.endereco ? <p className="mt-2 text-sm">{e.endereco}</p> : null}{e.status === "entregue" ? <p className="mt-3 text-sm">Recebido por {e.recebedor} · comprovante {e.comprovanteReferencia}</p> : null}{e.status === "falha_entrega" ? <p className="mt-3 text-sm text-red-700">Falha: {e.falhaMotivo}</p> : null}
      {podeGerenciar && e.status !== "entregue" ? <div className="mt-4 border-t border-(--border) pt-4"><div className="grid gap-3 sm:grid-cols-3"><div><label htmlFor={`recebedor-${e.id}`} className="workspace-label">Recebedor</label><input id={`recebedor-${e.id}`} className="workspace-input" value={recebedor} onChange={(x) => setRecebedor(x.target.value)} /></div><div><label htmlFor={`comprovante-${e.id}`} className="workspace-label">Referência do comprovante</label><input id={`comprovante-${e.id}`} className="workspace-input" value={comprovante} onChange={(x) => setComprovante(x.target.value)} /></div><div><label htmlFor={`obs-${e.id}`} className="workspace-label">Observação ou motivo da falha</label><input id={`obs-${e.id}`} className="workspace-input" value={observacao} onChange={(x) => setObservacao(x.target.value)} /></div></div><div className="mt-3 flex flex-wrap gap-2">{e.status === "pronto" ? <button className="workspace-button-secondary" onClick={() => void executar(() => repos.entregas.alterarStatus(empresaId, { entregaId: e.id, status: e.modalidade === "retirada" ? "aguardando_retirada" : "saiu_para_entrega", observacao, operacaoId: crypto.randomUUID() }, usuarioId), "Entrega atualizada.")}>{e.modalidade === "retirada" ? "Aguardar retirada" : "Registrar saída"}</button> : null}{e.status === "falha_entrega" ? <button className="workspace-button-secondary" onClick={() => void executar(() => repos.entregas.alterarStatus(empresaId, { entregaId: e.id, status: "saiu_para_entrega", observacao, operacaoId: crypto.randomUUID() }, usuarioId), "Nova tentativa registrada.")}>Nova tentativa</button> : null}{e.status === "saiu_para_entrega" ? <button className="workspace-button-danger" onClick={() => void executar(() => repos.entregas.alterarStatus(empresaId, { entregaId: e.id, status: "falha_entrega", observacao, operacaoId: crypto.randomUUID() }, usuarioId), "Falha registrada.")}>Registrar falha</button> : null}{["aguardando_retirada", "saiu_para_entrega"].includes(e.status) ? <button className="workspace-button-primary" onClick={() => void executar(() => repos.entregas.alterarStatus(empresaId, { entregaId: e.id, status: "entregue", recebedor, comprovanteReferencia: comprovante, observacao, operacaoId: crypto.randomUUID() }, usuarioId), "Entrega comprovada.")}>Confirmar entrega</button> : null}</div></div> : null}
      <ul className="mt-4 space-y-1 text-xs text-(--text-secondary)">{[...e.eventos].reverse().map((evento) => <li key={evento.id}>{new Date(evento.criadoEm).toLocaleString("pt-BR")} · {LABEL_STATUS[evento.status]}{evento.observacao ? ` · ${evento.observacao}` : ""}</li>)}</ul></SurfaceCard>)}</div>
  </div>;
}
