import { test, expect, type Page } from "@playwright/test";

async function semOverflow(page: Page) { expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true); }
test("compra parcial, saldo, reserva, consumo e perda persistem", async ({ page }, info) => {
  const erros: string[] = []; page.on("pageerror", (e) => erros.push(e.message));
  await page.goto("/login");
  await page.getByLabel("E-mail", { exact: true }).fill("gerente@graficanovaera.com.br");
  await page.getByLabel("Senha", { exact: true }).fill("demo123");
  await page.getByRole("button", { name: "Entrar", exact: true }).click(); await expect(page).toHaveURL(/\/$/);
  await page.goto("/compras");
  await page.getByLabel("Fornecedor", { exact: true }).selectOption("fornecedor-1");
  await page.getByLabel("Material da compra").selectOption("material-1");
  await page.getByLabel("Quantidade na unidade de compra").fill("2");
  await page.getByLabel("Preço por unidade de compra (R$)").fill("40");
  await page.getByRole("button", { name: "Adicionar item", exact: true }).click();
  await page.getByRole("button", { name: "Criar pedido de compra", exact: true }).click();
  await page.getByRole("button", { name: "Receber ou cancelar PC-0001" }).click();
  await page.getByLabel(/Receber Papel Couche/).fill("1");
  await page.getByLabel("Documento do recebimento").fill("NF-TESTE-1");
  await page.getByLabel("Vencimento da conta a pagar").fill("2026-10-10");
  await page.getByRole("button", { name: "Confirmar recebimento", exact: true }).click();
  await expect(page.getByText("parcial", { exact: true })).toBeVisible();
  await expect(page.getByText(/PC-0001 · Documento NF-TESTE-1/)).toBeVisible();
  await semOverflow(page); await page.screenshot({ path: info.outputPath("compras.png"), fullPage: true });
  await page.goto("/estoque");
  await expect(page.getByText("Disponível: 500 fl", { exact: true })).toBeVisible();
  await page.getByLabel("Material", { exact: true }).selectOption("material-1");
  await page.getByLabel("Estoque mínimo operacional").fill("450");
  await page.getByRole("button", { name: "Salvar parâmetros" }).click();
  await page.goto("/trabalhos/trabalho-1");
  await page.getByLabel("Material do consumo").selectOption("material-1");
  await page.getByLabel(/Quantidade operacional/).fill("200");
  await page.getByRole("button", { name: "Salvar previsão" }).click();
  await expect(page.getByText(/Previsto: 200 · Real: 0/)).toBeVisible();
  await page.getByLabel("Motivo do movimento").fill("Produção do cartão");
  await page.getByRole("button", { name: "Reservar material" }).click();
  await expect(page.getByText(/Reservado: 200 · Desvio/)).toBeVisible();
  await page.getByLabel(/Quantidade operacional/).fill("180");
  await page.getByRole("button", { name: "Registrar consumo" }).click();
  await expect(page.getByText(/Previsto: 200 · Real: 180 · Perda: 0/)).toBeVisible();
  await page.getByLabel(/Quantidade operacional/).fill("10");
  await page.getByRole("button", { name: "Registrar perda" }).click();
  await expect(page.getByText(/Previsto: 200 · Real: 180 · Perda: 10/)).toBeVisible();
  await page.reload(); await expect(page.getByText(/Previsto: 200 · Real: 180 · Perda: 10/)).toBeVisible();
  await semOverflow(page); await page.screenshot({ path: info.outputPath("consumo.png"), fullPage: true });
  await page.goto("/estoque");
  await expect(page.getByText("Disponível: 300 fl", { exact: true })).toBeVisible();
  await expect(page.getByText("Físico: 310 · Reservado: 10", { exact: true })).toBeVisible();
  await expect(page.getByText("Abaixo do mínimo", { exact: true })).toBeVisible();
  await semOverflow(page); await page.screenshot({ path: info.outputPath("estoque.png"), fullPage: true });
  expect(erros).toEqual([]);
});
