"use client";

import { useEffect, useState, useTransition } from "react";
import { useRepositoriosAutorizados as useRepositories, useSessao } from "@/components/providers/session-provider";
import { useToast } from "@/components/ui/toast";
import type { FeatureFlag } from "@/lib/domain/entities";

export function ParametrosAdmin() {
  const repos = useRepositories(), { sessao } = useSessao(), { showToast } = useToast(), empresaId = sessao?.empresaAtiva?.id;
  const [flags, setFlags] = useState<FeatureFlag[]>([]), [chave, setChave] = useState(""), [descricao, setDescricao] = useState(""), [pending, startTransition] = useTransition();
  async function carregar() { if (empresaId) setFlags(await repos.featureFlags.listar(empresaId)); }
  useEffect(() => { void carregar(); }, [empresaId]); // eslint-disable-line react-hooks/exhaustive-deps
  function executar(acao: () => Promise<unknown>, mensagem: string) { startTransition(async () => { try { await acao(); await carregar(); showToast(mensagem, "success"); } catch (e) { showToast(e instanceof Error ? e.message : "Falha ao salvar parâmetro.", "error"); } }); }
  if (!empresaId || !sessao) return null;
  return <div><p className="text-sm text-(--text-secondary)">Parâmetros funcionais simples usam o cadastro de feature flags já existente. Alterações ficam limitadas ao Administrador.</p><div className="mt-3 grid gap-3 sm:grid-cols-[1fr_2fr_auto]"><div><label htmlFor="param-chave" className="workspace-label">Chave</label><input id="param-chave" className="workspace-input" value={chave} onChange={(e) => setChave(e.target.value)} placeholder="ex.: exigir_aprovacao" /></div><div><label htmlFor="param-descricao" className="workspace-label">Descrição</label><input id="param-descricao" className="workspace-input" value={descricao} onChange={(e) => setDescricao(e.target.value)} /></div><button disabled={pending || !chave.trim()} className="workspace-button-primary self-end" onClick={() => executar(async () => { await repos.featureFlags.criar({ empresaId, chave: chave.trim(), habilitado: false, descricao: descricao.trim() || null }); await repos.auditoria.registrar({ empresaId, usuarioId: sessao.usuario.id, acao: "administracao.parametro_criar", entidade: "feature_flags", entidadeId: null, dadosAntes: null, dadosDepois: { chave: chave.trim() } }); setChave(""); setDescricao(""); }, "Parâmetro criado.")}>Adicionar</button></div><ul className="mt-4 space-y-2">{flags.map((flag) => <li className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-(--border) p-3" key={flag.id}><div><strong className="text-sm">{flag.chave}</strong><p className="text-xs text-(--text-secondary)">{flag.descricao ?? "Sem descrição"}</p></div><button disabled={pending} className={flag.habilitado ? "workspace-button-primary" : "workspace-button-secondary"} onClick={() => executar(async () => { await repos.featureFlags.atualizar(flag.id, { habilitado: !flag.habilitado }); await repos.auditoria.registrar({ empresaId, usuarioId: sessao.usuario.id, acao: "administracao.parametro_alterar", entidade: "feature_flags", entidadeId: flag.id, dadosAntes: { habilitado: flag.habilitado }, dadosDepois: { habilitado: !flag.habilitado } }); }, "Parâmetro atualizado.")}>{flag.habilitado ? "Habilitado" : "Desabilitado"}</button></li>)}</ul>{flags.length === 0 ? <p className="workspace-empty-state mt-3">Nenhum parâmetro adicional configurado.</p> : null}</div>;
}
