"use client";

import { useEffect, useState } from "react";
import { useRepositoriosAutorizados as useRepositories, useSessao } from "@/components/providers/session-provider";
import { MetricCard, PageIntro, SectionLabel, StatusPill, SurfaceCard } from "@/components/ui/workspace-primitives";
import type { RelatorioGestao } from "@/lib/domain/relatorios";
import { papelTemPermissao, PERMISSOES } from "@/lib/rbac";

const hoje = () => new Date().toISOString().slice(0, 10);
const inicioMes = () => `${hoje().slice(0, 7)}-01`;
const moeda = (valor: number) => valor.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const numero = (valor: number, casas = 1) => valor.toLocaleString("pt-BR", { maximumFractionDigits: casas });
const motivoLabel: Record<string, string> = { preco_alto: "Preço alto", prazo_incompativel: "Prazo incompatível", nao_precisa_mais: "Não precisa mais", concorrencia: "Concorrência", outro: "Outro" };

function Tabela({ cabecalhos, linhas }: { cabecalhos: string[]; linhas: (string | number)[][] }) {
  return <div className="mt-3 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="border-b border-(--border)">{cabecalhos.map((h) => <th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{linhas.map((linha, i) => <tr className="border-b border-(--border)" key={`${linha[0]}-${i}`}>{linha.map((valor, j) => <td className="p-2" key={`${j}-${valor}`}>{valor}</td>)}</tr>)}</tbody></table>{linhas.length === 0 ? <p className="workspace-empty-state mt-3">Sem dados no período.</p> : null}</div>;
}

export default function RelatoriosPage() {
  const repos = useRepositories(), { sessao } = useSessao(), empresaId = sessao?.empresaAtiva?.id;
  const permitido = sessao?.empresaAtiva ? papelTemPermissao(sessao.empresaAtiva.papel, PERMISSOES.RELATORIOS_CONSULTAR) : false;
  const [inicio, setInicio] = useState(inicioMes), [fim, setFim] = useState(hoje), [relatorio, setRelatorio] = useState<RelatorioGestao | null>(null), [erro, setErro] = useState<string | null>(null);
  useEffect(() => { if (!empresaId || !permitido) return; let ativo = true; repos.relatorios.gerar(empresaId, { inicio, fim }).then((r) => { if (ativo) { setRelatorio(r); setErro(null); } }).catch((e) => { if (ativo) setErro(e instanceof Error ? e.message : "Falha ao gerar relatórios."); }); return () => { ativo = false; }; }, [empresaId, fim, inicio, permitido, repos]);
  if (!empresaId) return null;
  if (!permitido) return <SurfaceCard className="p-5"><p className="text-sm text-(--text-secondary)">Seu papel atual não tem acesso aos relatórios gerenciais.</p></SurfaceCard>;
  return <div className="flex flex-col gap-4">
    <PageIntro eyebrow="Gestão" title="Relatórios" description="Leituras consolidadas de vendas, produção, estoque, compras, financeiro, clientes e equipamentos, sem criar domínios paralelos." aside={<StatusPill tone="accent">{inicio.split("-").reverse().join("/")} a {fim.split("-").reverse().join("/")}</StatusPill>} />
    <SurfaceCard className="p-5"><div className="flex flex-wrap gap-3"><div><label htmlFor="rel-inicio" className="workspace-label">Início</label><input id="rel-inicio" type="date" className="workspace-input" value={inicio} onChange={(e) => setInicio(e.target.value)} /></div><div><label htmlFor="rel-fim" className="workspace-label">Fim</label><input id="rel-fim" type="date" className="workspace-input" value={fim} onChange={(e) => setFim(e.target.value)} /></div></div>{erro ? <p className="mt-3 text-sm text-red-700">{erro}</p> : null}</SurfaceCard>
    {relatorio ? <>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Vendas" value={moeda(relatorio.vendas.valor)} helper={`${relatorio.vendas.pedidos} Pedidos, ticket ${moeda(relatorio.vendas.ticketMedio)}`} /><MetricCard label="Conversão" value={`${numero(relatorio.orcamentos.taxaConversao)}%`} helper={`${relatorio.orcamentos.aprovados} aprovados de ${relatorio.orcamentos.enviados}`} /><MetricCard label="Resultado de caixa" value={moeda(relatorio.financeiro.resultadoCaixa)} helper={`Recebido ${moeda(relatorio.financeiro.recebido)}`} /><MetricCard label="Estoque crítico" value={relatorio.estoque.itensCriticos} helper={`Perdas ${numero(relatorio.estoque.perdas)} unidades operacionais`} /></div>
      <div className="grid gap-4 xl:grid-cols-2"><SurfaceCard className="p-5"><SectionLabel>Vendas por dia</SectionLabel><Tabela cabecalhos={["Data", "Pedidos", "Valor"]} linhas={relatorio.vendas.porDia.map((x) => [x.chave.split("-").reverse().join("/"), x.quantidade, moeda(x.valor)])} /></SurfaceCard><SurfaceCard className="p-5"><SectionLabel>Orçamentos e rejeições</SectionLabel><div className="mt-3 grid grid-cols-3 gap-2 text-center text-sm"><div><strong className="block text-xl">{relatorio.orcamentos.enviados}</strong>Enviados</div><div><strong className="block text-xl">{relatorio.orcamentos.aprovados}</strong>Aprovados</div><div><strong className="block text-xl">{relatorio.orcamentos.rejeitados}</strong>Rejeitados</div></div><Tabela cabecalhos={["Motivo", "Quantidade"]} linhas={relatorio.orcamentos.motivosRejeicao.map((x) => [motivoLabel[x.motivo] ?? x.motivo, x.quantidade])} /></SurfaceCard></div>
      <div className="grid gap-4 xl:grid-cols-2"><SurfaceCard className="p-5"><SectionLabel>Produção</SectionLabel><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3"><MetricCard label="Criados" value={relatorio.producao.criados} /><MetricCard label="Concluídos" value={relatorio.producao.concluidos} /><MetricCard label="Em andamento" value={relatorio.producao.emAndamento} /><MetricCard label="Atrasados" value={relatorio.producao.atrasados} /><MetricCard label="Tempo médio" value={`${numero(relatorio.producao.tempoMedioHoras)}h`} /><MetricCard label="Retrabalho proxy" value={relatorio.producao.retrabalhosProxy} helper="Novas versões de arquivo" /></div></SurfaceCard><SurfaceCard className="p-5"><SectionLabel>Compras e financeiro</SectionLabel><Tabela cabecalhos={["Indicador", "Valor"]} linhas={[["Compras solicitadas", moeda(relatorio.compras.valorSolicitado)], ["Compras recebidas", moeda(relatorio.compras.valorRecebido)], ["Pedidos de compra pendentes", relatorio.compras.pendentes], ["Contas a receber", moeda(relatorio.financeiro.contasReceber)], ["Contas a pagar", moeda(relatorio.financeiro.contasPagar)], ["Despesas pagas", moeda(relatorio.financeiro.despesasPagas)]]} /></SurfaceCard></div>
      <SurfaceCard className="p-5"><SectionLabel>Estoque, consumo e perdas</SectionLabel><p className="mt-2 text-sm text-(--text-secondary)">Consumo no período: {numero(relatorio.estoque.consumo)}. Perdas no período: {numero(relatorio.estoque.perdas)}. Quantidades usam a unidade operacional de cada material.</p><Tabela cabecalhos={["Material", "Físico", "Reservado", "Disponível", "Mínimo", "Situação"]} linhas={relatorio.estoque.itens.map((x) => [x.nome, `${numero(x.fisico)} ${x.unidade}`, `${numero(x.reservado)} ${x.unidade}`, `${numero(x.disponivel)} ${x.unidade}`, `${numero(x.minimo)} ${x.unidade}`, x.abaixoMinimo ? "Crítico" : "Normal"])} /></SurfaceCard>
      <div className="grid gap-4 xl:grid-cols-2"><SurfaceCard className="p-5"><SectionLabel>Clientes</SectionLabel><Tabela cabecalhos={["Cliente", "Pedidos", "Vendas", "Recebido"]} linhas={relatorio.clientes.map((x) => [x.nome, x.pedidos, moeda(x.valor), moeda(x.recebido)])} /></SurfaceCard><SurfaceCard className="p-5"><SectionLabel>Equipamentos</SectionLabel><Tabela cabecalhos={["Equipamento", "Alocações", "Concluídas", "Horas", "Situação"]} linhas={relatorio.equipamentos.map((x) => [x.nome, x.alocacoes, x.concluidas, numero(x.horasExecutadas), x.situacao])} /></SurfaceCard></div>
      <SurfaceCard className="p-5" muted><SectionLabel>Critérios de leitura</SectionLabel><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-(--text-secondary)">{relatorio.observacoes.map((o) => <li key={o}>{o}</li>)}</ul></SurfaceCard>
    </> : <SurfaceCard className="p-5"><p className="text-sm text-(--text-secondary)">Carregando consolidação...</p></SurfaceCard>}
  </div>;
}
