"use client";

import { useEffect, useMemo, useState } from "react";
import { PageIntro, SectionLabel, StatusPill, SurfaceCard } from "@/components/ui/workspace-primitives";
import { useToast } from "@/components/ui/toast";
import { useRepositoriosAutorizados as useRepositories, useSessao } from "@/components/providers/session-provider";
import type { Cliente, Contato, EmailContato, Pedido } from "@/lib/domain/entities";
import type { ConvitePortalCliente, TokenPedidoPortal } from "@/lib/domain/portal-cliente";

export default function PortalClientesGestaoPage() {
  const repos = useRepositories(), { sessao } = useSessao(), { showToast } = useToast();
  const empresaId = sessao?.empresaAtiva?.id, usuarioId = sessao?.usuario.id;
  const [clientes, setClientes] = useState<Cliente[]>([]), [contatos, setContatos] = useState<Contato[]>([]), [emails, setEmails] = useState<EmailContato[]>([]), [pedidos, setPedidos] = useState<Pedido[]>([]), [convites, setConvites] = useState<ConvitePortalCliente[]>([]), [tokens, setTokens] = useState<TokenPedidoPortal[]>([]);
  const [clienteId, setClienteId] = useState(""), [email, setEmail] = useState(""), [pedidoId, setPedidoId] = useState(""), [dias, setDias] = useState("7"), [link, setLink] = useState("");
  const emailsCliente = useMemo(() => { const ids = new Set(contatos.filter((c) => c.clienteId === clienteId).map((c) => c.id)); return emails.filter((e) => ids.has(e.contatoId)); }, [clienteId, contatos, emails]);
  async function carregar() { if (!empresaId) return; const [cs, cts, es, ps, cvs, ts] = await Promise.all([repos.clientes.listar(empresaId), repos.contatos.listar(empresaId), repos.emailsContato.listar(empresaId), repos.pedidos.listar(empresaId), repos.portalClienteGestao.listarConvites(empresaId), repos.portalClienteGestao.listarTokensPedido(empresaId)]); setClientes(cs); setContatos(cts); setEmails(es); setPedidos(ps); setConvites(cvs); setTokens(ts); if (!clienteId && cs[0]) setClienteId(cs[0].id); if (!pedidoId && ps[0]) setPedidoId(ps[0].id); }
  useEffect(() => { void carregar(); }, [empresaId]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (emailsCliente[0] && !emailsCliente.some((e) => e.email === email)) setEmail(emailsCliente[0].email); }, [emailsCliente, email]);
  async function executar(acao: () => Promise<void>, mensagem: string) { try { await acao(); showToast(mensagem, "success"); await carregar(); } catch (erro) { showToast(erro instanceof Error ? erro.message : "Falha na operação.", "error"); } }
  if (!empresaId || !usuarioId) return null;
  const url = (rota: string) => `${window.location.origin}${rota}`;
  return <div className="flex flex-col gap-4"><PageIntro eyebrow="Portal do cliente" title="Acessos e links" description="Convide contatos para criar conta ou gere um link temporário para apenas um Pedido. Tokens podem ser revogados a qualquer momento." />
    <div className="grid gap-4 xl:grid-cols-2"><SurfaceCard className="p-5"><SectionLabel>Convidar para criar conta</SectionLabel><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><label htmlFor="portal-cliente" className="workspace-label">Cliente</label><select id="portal-cliente" className="workspace-input" value={clienteId} onChange={(e) => setClienteId(e.target.value)}>{clientes.map((c) => <option key={c.id} value={c.id}>{c.nome}</option>)}</select></div><div><label htmlFor="portal-email" className="workspace-label">E-mail cadastrado</label><select id="portal-email" className="workspace-input" value={email} onChange={(e) => setEmail(e.target.value)}>{emailsCliente.map((e) => <option key={e.id} value={e.email}>{e.email}</option>)}</select></div></div><button className="workspace-button-primary mt-3" onClick={() => void executar(async () => { const convite = await repos.portalClienteGestao.convidar(empresaId, { clienteId, email, validadeDias: Number(dias), operacaoId: crypto.randomUUID() }, usuarioId); setLink(url(`/portal/acesso?convite=${convite.token}`)); }, "Convite criado.")}>Gerar convite</button></SurfaceCard>
      <SurfaceCard className="p-5"><SectionLabel>Link temporário de Pedido</SectionLabel><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><label htmlFor="portal-pedido" className="workspace-label">Pedido</label><select id="portal-pedido" className="workspace-input" value={pedidoId} onChange={(e) => setPedidoId(e.target.value)}>{pedidos.map((p) => <option key={p.id} value={p.id}>{p.numero}</option>)}</select></div><div><label htmlFor="portal-validade" className="workspace-label">Validade em dias</label><input id="portal-validade" type="number" min="1" max="90" className="workspace-input" value={dias} onChange={(e) => setDias(e.target.value)} /></div></div><button className="workspace-button-primary mt-3" onClick={() => void executar(async () => { const token = await repos.portalClienteGestao.emitirTokenPedido(empresaId, { pedidoId, validadeDias: Number(dias), operacaoId: crypto.randomUUID() }, usuarioId); setLink(url(`/portal/pedido/${token.token}`)); }, "Link criado.")}>Gerar link</button></SurfaceCard></div>
    {link ? <SurfaceCard className="p-5"><SectionLabel>Link gerado</SectionLabel><p className="mt-2 break-all text-sm">{link}</p><button className="workspace-button-secondary mt-3" onClick={() => void navigator.clipboard.writeText(link)}>Copiar link</button></SurfaceCard> : null}
    <div className="grid gap-4 xl:grid-cols-2"><SurfaceCard className="p-5"><SectionLabel>Convites</SectionLabel><ul className="mt-3 space-y-2">{convites.map((c) => <li key={c.id} className="rounded-lg border border-(--border) p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><span>{c.email}</span><StatusPill tone={c.revogadoEm || c.expiraEm <= new Date().toISOString() ? "danger" : c.usadoEm ? "success" : "warning"}>{c.revogadoEm ? "revogado" : c.usadoEm ? "utilizado" : "ativo"}</StatusPill></div>{!c.revogadoEm && !c.usadoEm ? <button className="workspace-button-secondary mt-2" onClick={() => void executar(() => repos.portalClienteGestao.revogarConvite(empresaId, c.id, usuarioId), "Convite revogado.")}>Revogar</button> : null}</li>)}</ul></SurfaceCard><SurfaceCard className="p-5"><SectionLabel>Links de Pedido</SectionLabel><ul className="mt-3 space-y-2">{tokens.map((t) => <li key={t.id} className="rounded-lg border border-(--border) p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><span>{pedidos.find((p) => p.id === t.pedidoId)?.numero}</span><StatusPill tone={t.revogadoEm || t.expiraEm <= new Date().toISOString() ? "danger" : "success"}>{t.revogadoEm ? "revogado" : "ativo"}</StatusPill></div>{!t.revogadoEm ? <button className="workspace-button-secondary mt-2" onClick={() => void executar(() => repos.portalClienteGestao.revogarTokenPedido(empresaId, t.id, usuarioId), "Link revogado.")}>Revogar</button> : null}</li>)}</ul></SurfaceCard></div>
  </div>;
}
