"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useRepositories } from "@/lib/repositories";
import type { PainelPortalCliente, PedidoPortal } from "@/lib/domain/portal-cliente";
import { StatusPill } from "@/components/ui/workspace-primitives";

const moeda = (v: number) => v.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const status = (p: PedidoPortal) => p.pedido.statusEntrega === "concluido" ? "Concluído" : p.pedido.statusEntrega === "cancelado" ? "Cancelado" : "Em andamento";

function CartaoPedido({ item }: { item: PedidoPortal }) {
  return <article className="rounded-2xl border border-(--border) bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-(--text-tertiary)">{new Date(item.pedido.criadoEm).toLocaleDateString("pt-BR")}</p><h3 className="text-lg font-semibold">{item.pedido.numero}</h3></div><StatusPill tone={item.pedido.statusEntrega === "concluido" ? "success" : item.pedido.statusEntrega === "cancelado" ? "danger" : "warning"}>{status(item)}</StatusPill></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><div className="rounded-xl bg-(--bg-muted) p-3 text-sm"><span className="block text-xs text-(--text-tertiary)">Total</span>{moeda(item.pedido.valorTotal)}</div><div className="rounded-xl bg-(--bg-muted) p-3 text-sm"><span className="block text-xs text-(--text-tertiary)">Recebido</span>{moeda(item.recebido)}</div><div className="rounded-xl bg-(--bg-muted) p-3 text-sm"><span className="block text-xs text-(--text-tertiary)">Saldo</span>{moeda(item.saldo)}</div></div>{item.trabalhos.length ? <div className="mt-4"><p className="text-xs font-semibold uppercase tracking-wide text-(--text-tertiary)">Produção e previsão</p>{item.trabalhos.map((t) => <p key={t.id} className="mt-1 text-sm">{t.codigo} · {t.workflow.etapas.find((e) => e.id === t.etapaAtualId)?.nome ?? t.situacao}{t.prazo ? ` · previsão ${new Date(t.prazo).toLocaleDateString("pt-BR")}` : ""}</p>)}</div> : null}{item.arquivosLiberados.length ? <div className="mt-4"><p className="text-xs font-semibold uppercase tracking-wide text-(--text-tertiary)">Arquivos liberados</p>{item.arquivosLiberados.map((a) => <p key={a.id} className="mt-1 text-sm">{a.nome} · versão {a.versao} · referência {a.referenciaMock ?? "externa"}</p>)}</div> : null}{item.orcamento ? <p className="mt-4 text-sm">Orçamento {item.orcamento.numero} · versão {item.orcamento.versao} · {item.orcamento.status}</p> : null}<p className="mt-4 text-sm"><strong>Entrega:</strong> {item.entrega ? `${item.entrega.status.replaceAll("_", " ")}${item.entrega.previsao ? ` · previsão ${item.entrega.previsao.split("-").reverse().join("/")}` : ""}${item.entrega.codigoRastreio ? ` · rastreio ${item.entrega.codigoRastreio}` : ""}` : "a definir pela gráfica"}</p>{item.entrega?.status === "entregue" ? <p className="mt-1 text-xs text-(--text-tertiary)">Recebido por {item.entrega.recebedor} · comprovante {item.entrega.comprovanteReferencia}</p> : null}</article>;
}

export default function PortalClientePage() {
  const repos = useRepositories(), router = useRouter(); const [painel, setPainel] = useState<PainelPortalCliente | null | undefined>(undefined);
  useEffect(() => { void repos.portalCliente.obterPainel().then((p) => { setPainel(p); if (!p) router.replace("/portal/acesso"); }); }, [repos, router]);
  if (painel === undefined || painel === null) return null;
  return <main className="mx-auto min-h-screen w-full max-w-5xl px-4 py-8"><header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.24em] text-(--accent)">Portal do cliente</p><h1 className="mt-1 text-2xl font-semibold">Seus pedidos</h1><p className="text-sm text-(--text-secondary)">{painel.email}</p></div><button className="workspace-button-secondary" onClick={() => void repos.portalCliente.sair().then(() => router.replace("/portal/acesso"))}>Sair</button></header><section className="mt-6"><h2 className="text-lg font-semibold">Pedidos ativos</h2><div className="mt-3 grid gap-4">{painel.pedidosAtivos.map((p) => <CartaoPedido key={p.pedido.id} item={p} />)}{!painel.pedidosAtivos.length ? <p className="workspace-empty-state">Nenhum pedido ativo.</p> : null}</div></section><section className="mt-8"><h2 className="text-lg font-semibold">Histórico</h2><div className="mt-3 grid gap-4">{painel.historico.map((p) => <CartaoPedido key={p.pedido.id} item={p} />)}{!painel.historico.length ? <p className="workspace-empty-state">Nenhum pedido no histórico.</p> : null}</div></section><section className="mt-8 rounded-2xl border border-(--border) bg-white p-5"><h2 className="text-lg font-semibold">Orçamentos</h2><ul className="mt-3 space-y-2">{painel.orcamentos.map((o) => <li key={o.id} className="flex flex-wrap items-center justify-between gap-2 border-b border-(--border) py-2 text-sm"><span>{o.numero} · V{o.versao}</span><span>{o.status} · {moeda(o.valorTotal)}{o.status === "enviado" ? <a className="ml-3 font-semibold text-(--accent-strong) underline" href={`/portal/orcamento/${o.tokenAcompanhamento}`}>Analisar</a> : null}</span></li>)}</ul></section></main>;
}
